apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app-chart.fullname" . }}
  labels:
    {{- include "app-chart.labels" . | nindent 4 }}
data:
  APP_MESSAGE: "{{ .Values.env.APP_MESSAGE }}"
